apiVersion: v1
kind: ConfigMap
metadata:
    name: shopping-cart-config
    namespace: dev

data:
    APP_NAME: "Shopping Cart Application"
    ENV: "Development"
    DB_HOST: "mysql-db"
    DB_PORT: "3306"
    MYSQL_DATABASE: "ecom_db"
    LOG_LEVEL: "INFO"